import{a as _,i as d,S as m}from"./assets/vendor-cc6936ea.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const S="43843961-af0153872675268c29353c689",w="https://pixabay.com/api/";async function g(r,n){const s=new URLSearchParams({key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15});try{return(await _.get(`${w}?${s}&page=${n}`)).data}catch(o){console.error(o)}}function y(r){r.style.display="flex"}function u(r){r.style.display="none"}function E(r){r.classList.remove("hidden")}function h(r){r.classList.add("hidden")}function b(r){return r.map(({webformatURL:n,largeImageURL:s,tags:o,likes:e,views:t,comments:a,downloads:l})=>`
        <div class="photo-card">
          <a href="${s}" target="_blank">
            <img src="${n}" alt="${o}" loading="lazy" class="photo-card__image" />
          </a>
          <div class="photo-card__info">
            <p class="photo-card__info-item"><b>Likes:</b> ${e}</p>
            <p class="photo-card__info-item"><b>Views:</b> ${t}</p>
            <p class="photo-card__info-item"><b>Comments:</b> ${a}</p>
            <p class="photo-card__info-item"><b>Downloads:</b> ${l}</p>
          </div>
        </div>
      `).join("")}function q(){const r=document.querySelector(".gallery");r.innerHTML=""}document.addEventListener("DOMContentLoaded",function(){const r=document.querySelector("#search-form"),n=document.querySelector("#search-input"),s=document.querySelector(".gallery"),o=document.querySelector(".loader-container"),e=document.querySelector(".load-more");h(e),u(o);let t="",a=1,l=0;r.addEventListener("submit",L),e.addEventListener("click",v);function L(c){if(c.preventDefault(),t=n.value.trim(),a=1,q(),y(o),h(e),t===""){d.error({title:"Error",message:"Please enter a search query!"}),n.value="",u(o);return}g(t,a).then(i=>{if(i.hits&&i.hits.length>0){const f=b(i.hits);s.insertAdjacentHTML("beforeend",f),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),l=i.totalHits,s.children.length<l&&E(e)}else d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});n.value=""}).catch(i=>{d.error({title:"Error",message:i.message}),n.value=""}).finally(()=>u(o))}function v(){a+=1,y(o),g(t,a).then(c=>{if(c.hits&&c.hits.length>0){const i=b(c.hits);s.insertAdjacentHTML("beforeend",i),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),s.children.length>=l&&(h(e),d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:p}=s.firstElementChild.getBoundingClientRect();window.scrollBy({top:p*2,behavior:"smooth"})}else h(e)}).catch(c=>{d.error({title:"Error",message:c.message})}).finally(()=>u(o))}});
//# sourceMappingURL=commonHelpers.js.map
