import{a as E,i as h,S as m}from"./assets/vendor-cc6936ea.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="43843961-af0153872675268c29353c689",x="https://pixabay.com/api/";async function y(t,r){const s=new URLSearchParams({key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15});try{return(await E.get(`${x}?${s}&page=${r}`)).data}catch(n){console.error(n)}}function M(t){t.style.display="flex"}function f(t){t.style.display="none"}function g(t){t.classList.remove("hidden")}function L(t){t.classList.add("hidden")}function $(t){t.classList.remove("hidden")}function b(t){t.classList.add("hidden")}function v(t){return t.map(({webformatURL:r,largeImageURL:s,tags:n,likes:e,views:o,comments:i,downloads:l})=>`
        <div class="photo-card">
          <a href="${s}" target="_blank">
            <img src="${r}" alt="${n}" loading="lazy" class="photo-card__image" />
          </a>
          <div class="photo-card__info">
            <p class="photo-card__info-item"><b>Likes:</b> ${e}</p>
            <p class="photo-card__info-item"><b>Views:</b> ${o}</p>
            <p class="photo-card__info-item"><b>Comments:</b> ${i}</p>
            <p class="photo-card__info-item"><b>Downloads:</b> ${l}</p>
          </div>
        </div>
      `).join("")}function A(){const t=document.querySelector(".gallery");t.innerHTML=""}document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector("#search-form"),r=document.querySelector("#search-input"),s=document.querySelector(".gallery"),n=document.querySelector(".loader-container"),e=document.querySelector(".load-more"),o=document.querySelector(".loader-btn");setTimeout(()=>{f(n)},1e3);let i="",l=1,d=0;t.addEventListener("submit",_),e.addEventListener("click",w);function _(a){if(a.preventDefault(),i=r.value.trim(),i===""){h.error({title:"Error",message:"Please enter a search query!"}),r.value="",f(n);return}A(),M(n),L(e),y(i,l).then(c=>{if(!c.hits||!Array.isArray(c.hits))throw new Error("Unexpected response format");const u=c.hits,p=v(u);s.insertAdjacentHTML("beforeend",p),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),d=c.totalHits,d>s.children.length&&g(e),r.value=""}).catch(c=>{h.error({title:"Error",message:c.message}),r.value=""}).finally(()=>f(n))}function w(){l+=1,$(o),y(i,l).then(a=>{if(b(o),!a.hits||!Array.isArray(a.hits))throw new Error("Unexpected response format");const c=a.hits,u=v(c);s.insertAdjacentHTML("beforeend",u),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),d>s.children.length?g(e):L(e),S()}).catch(a=>{b(o),h.error({title:"Error",message:a.message})})}function S(){const{height:a}=s.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}});
//# sourceMappingURL=commonHelpers.js.map
